const mongoose = require("mongoose");
const { randomUUID } = require("crypto");

const transactionSchema = new mongoose.Schema(
  {
    fromAccount: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "account",
      required: [true, "Transaction must be associated to a FROM account"],
      index: true,
    },
    toAccount: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "account",
      required: [true, "Transaction must be associated to a FROM account"],
      index: true,
    },
    status: {
      type: String,
      enum: {
        values: ["PENDING", "COMPLETED", "FAILED", "REVERSED"],
        message: "Status can be either PENDING, COMPLETED, FAILED or REVERSED",
      },
      default: "PENDING",
    },
    amount: {
      type: Number,
      required: [true, "Amount is required for creating a transaction"],
      min: [0, "Transaction cannot be negative"],
    },
    //generated by client side
    idempotencyKey: {
      type: String,
      required: [
        true,
        "Idempotency Key is required for creating a transaction",
      ],
      trim: true,
      index: true,
      unique: true,
      sparse: true,
      default: () => randomUUID(),
    },
  },
  {
    timestamps: true,
  },
);

const TransactionModel = mongoose.model("transaction",transactionSchema);

module.exports = TransactionModel;
